pipeline {
   agent any
   stages {
     stage("build"){
       steps{
         echo "Hello World  Building an application"
       }
     }
       stage ("test"){
         steps{
           echo "testing an application"
         }
       }

          stage("Deploy"){
       steps{
         echo "Deploying an applictaion"
        }
      }

  }
}  
  
  
